"""Independent NumPy window oracle, not expectations generated by the kernel."""

import numpy as np
import pandas as pd
import pytest

from easy_tdx.factor import FactorEngine, get_factor, list_factors
from easy_tdx.factor.builtin.alpha158 import SPECS, compute_alpha158
from easy_tdx.factor.catalog import describe_factor
from easy_tdx.web.routers.research import (
    FactorComputeRequest,
    FactorEvaluationRequest,
    _factor_result,
)
from tests.market_matrix import entries, load_case


def sample(n=145):
    rng = np.random.default_rng(187)
    c = 25 + np.cumsum(rng.normal(0, 0.3, n))
    o = c + rng.normal(0, 0.1, n)
    return pd.DataFrame(
        {
            "open": o,
            "close": c,
            "high": np.maximum(o, c) + 0.4,
            "low": np.minimum(o, c) - 0.5,
            "volume": rng.integers(100, 10000, n).astype(float),
            "vwap": (o + c) / 2,
        },
        index=pd.date_range("2020-01-01", periods=n),
    )


def oracle(data, key, i, *, spec=None):
    """Scalar array operations / least squares; no production rolling helpers."""
    s = spec if spec is not None else SPECS[key]
    if i + 1 < s.warmup:
        return np.nan
    values = data.iloc[i - s.warmup + 1 : i + 1][list(s.inputs)].to_numpy()
    if not np.isfinite(values).all():
        return np.nan
    row = data.iloc[i]
    o, h, low_price, c = (row[k] for k in ("open", "high", "low", "close"))
    eps = 1e-12
    f, w = s.family, s.window
    if w is None:
        fixed = {
            "KMID": (c - o) / o,
            "KLEN": (h - low_price) / o,
            "KMID2": (c - o) / (h - low_price + eps),
            "KUP": (h - max(o, c)) / o,
            "KUP2": (h - max(o, c)) / (h - low_price + eps),
            "KLOW": (min(o, c) - low_price) / o,
            "KLOW2": (min(o, c) - low_price) / (h - low_price + eps),
            "KSFT": (2 * c - h - low_price) / o,
            "KSFT2": (2 * c - h - low_price) / (h - low_price + eps),
            "OPEN0": o / c,
            "HIGH0": h / c,
            "LOW0": low_price / c,
            "VWAP0": row.get("vwap", np.nan) / c,
        }
        return fixed[f]
    a = data.iloc[i - w + 1 : i + 1]
    close, high, low = (a[k].to_numpy() for k in ("close", "high", "low"))
    vol = a["volume"].to_numpy() if "volume" in a else None
    if f == "ROC":
        return data.close.iloc[i - w] / c
    if f == "MA":
        return np.mean(close) / c
    if f == "STD":
        return np.std(close, ddof=1) / c
    if f in {"BETA", "RESI", "RSQR"}:
        x = np.column_stack([np.arange(w), np.ones(w)])
        coeff = np.linalg.lstsq(x, close, rcond=None)[0]
        fitted = x @ coeff
        if f == "BETA":
            return coeff[0] / c
        if f == "RESI":
            return (c - fitted[-1]) / c
        if np.isclose(np.std(close, ddof=1), 0, atol=2e-5):
            return np.nan
        return 1 - sum((close - fitted) ** 2) / sum((close - np.mean(close)) ** 2)
    if f == "MAX":
        return max(high) / c
    if f == "MIN":
        return min(low) / c
    if f == "QTLU":
        return np.quantile(close, 0.8) / c
    if f == "QTLD":
        return np.quantile(close, 0.2) / c
    if f == "RANK":
        return (sum(close < c) + (sum(close == c) + 1) / 2) / w
    if f == "RSV":
        return (c - min(low)) / (max(high) - min(low) + eps)
    if f == "IMAX":
        return (list(high).index(max(high)) + 1) / w
    if f == "IMIN":
        return (list(low).index(min(low)) + 1) / w
    if f == "IMXD":
        return (list(high).index(max(high)) - list(low).index(min(low))) / w
    previous = data.iloc[i - w : i].close.to_numpy()
    previous_vol = data.iloc[i - w : i].volume.to_numpy() if "volume" in data else None
    if f in {"CORR", "CORD"}:
        x = close if f == "CORR" else close / previous
        y = np.log(vol + 1) if f == "CORR" else np.log(vol / previous_vol + 1)
        if np.isclose(np.std(x, ddof=1), 0, atol=2e-5) or np.isclose(
            np.std(y, ddof=1), 0, atol=2e-5
        ):
            return np.nan
        return np.corrcoef(x, y)[0, 1]
    if f.startswith("CNT"):
        pos, neg = sum(close > previous) / w, sum(close < previous) / w
        return pos if f == "CNTP" else neg if f == "CNTN" else pos - neg
    if f.startswith(("SUM", "VSUM")):
        delta = vol - previous_vol if f.startswith("V") else close - previous
        pos = sum(v for v in delta if v > 0)
        neg = -sum(v for v in delta if v < 0)
        return (pos if f.endswith("P") else neg if f.endswith("N") else pos - neg) / (
            sum(abs(delta)) + eps
        )
    if f == "VMA":
        return np.mean(vol) / (vol[-1] + eps)
    if f == "VSTD":
        return np.std(vol, ddof=1) / (vol[-1] + eps)
    if f == "WVMA":
        z = abs(close / previous - 1) * vol
        return np.std(z, ddof=1) / (np.mean(z) + eps)
    raise AssertionError(f)


@pytest.mark.parametrize("key", SPECS)
def test_every_formula_every_default_window_against_independent_oracle(key):
    data = sample()
    actual = get_factor(f"alpha158_{key.lower()}")().compute(data)
    expected = [oracle(data, key, i) for i in range(len(data))]
    np.testing.assert_allclose(actual, expected, rtol=2e-8, atol=2e-10, equal_nan=True)
    assert actual.index.equals(data.index)


@pytest.mark.parametrize("key", SPECS)
def test_every_formula_is_causal_and_missing_window_is_not_filled(key):
    data = sample()
    spec = SPECS[key]
    whole = compute_alpha158(data, spec)
    prefix = compute_alpha158(data.iloc[:83], spec)
    pd.testing.assert_series_equal(whole.iloc[:83], prefix)
    broken = data.copy()
    broken.loc[broken.index[70], spec.inputs[0]] = np.nan
    result = compute_alpha158(broken, spec)
    assert result.iloc[70 : 70 + spec.warmup].isna().all()
    pd.testing.assert_series_equal(result.iloc[70 + spec.warmup :], whole.iloc[70 + spec.warmup :])


def test_hand_calculated_ties_and_official_roc_direction():
    data = sample(8)
    data.loc[:, "close"] = [1, 2, 2, 4, 2, 5, 5, 5]
    data.loc[:, "high"] = [2, 5, 5, 4, 3, 6, 6, 6]
    data.loc[:, "low"] = [0.5, 1, 1, 1, 1, 2, 2, 2]
    assert compute_alpha158(data, SPECS["RANK5"]).iloc[4] == 0.6
    assert compute_alpha158(data, SPECS["IMAX5"]).iloc[4] == 0.4
    assert compute_alpha158(data, SPECS["IMIN5"]).iloc[4] == 0.2
    assert compute_alpha158(data, SPECS["ROC5"]).iloc[5] == 0.2  # not +400%
    assert compute_alpha158(data, SPECS["CNTP5"]).iloc[5] == 0.6
    assert compute_alpha158(data, SPECS["SUMP5"]).iloc[5] == pytest.approx(0.75)


def test_constant_zero_denominator_and_invalid_input():
    data = sample(80)
    data.loc[:, ["open", "high", "low", "close", "vwap"]] = 10.0
    data.loc[:, "volume"] = 0.0
    for key in SPECS:
        value = compute_alpha158(data, SPECS[key])
        assert not np.isinf(value).any()
    for key in ["RSQR5", "CORR5", "CORD5"]:
        assert compute_alpha158(data, SPECS[key]).isna().all()
    assert compute_alpha158(data, SPECS["KMID2"]).eq(0).all()
    assert compute_alpha158(data, SPECS["RANK5"]).iloc[-1] == 0.6
    assert compute_alpha158(data, SPECS["VMA5"]).iloc[-1] == 0
    for bad in [0.0, -1.0, np.inf, np.nan]:
        data.loc[data.index[-1], "close"] = bad
        assert np.isnan(compute_alpha158(data, SPECS["MA5"]).iloc[-1])
    with pytest.raises(ValueError, match="索引"):
        compute_alpha158(data.iloc[::-1], SPECS["MA5"])
    with pytest.raises(ValueError, match="缺少字段"):
        compute_alpha158(data.drop(columns="volume"), SPECS["VMA5"])


def test_registry_counts_and_no_native_volume_or_vwap_substitution():
    fixed = "KMID KLEN KMID2 KUP KUP2 KLOW KLOW2 KSFT KSFT2 OPEN0 HIGH0 LOW0 VWAP0".split()
    rolling = (
        "ROC MA STD BETA RSQR RESI MAX MIN QTLU QTLD RANK RSV IMAX IMIN IMXD "
        "CORR CORD CNTP CNTN CNTD SUMP SUMN SUMD VMA VSTD WVMA VSUMP VSUMN VSUMD"
    ).split()
    assert set(SPECS) == set(fixed) | {f"{f}{w}" for f in rolling for w in [5, 10, 20, 30, 60]}
    catalog = [f for f in list_factors() if f["library"] == "qlib_alpha158"]
    assert len(catalog) == 158
    assert sum(f["implemented"] for f in catalog) == 158
    assert sum(f["available"] for f in catalog) == 158
    from easy_tdx.factor.catalog import availability_reason

    assert sum(not availability_reason(f, "QFQ") for f in catalog) == 157
    assert sum(not availability_reason(f, "NONE") for f in catalog) == 158
    assert len({f["formula_sha256"] for f in catalog}) == 158
    data = sample().drop(columns=["volume", "vwap"])
    data["vol"] = 100  # must not silently alias an unverified native unit
    data["amount"] = 1000
    req = FactorComputeRequest(
        market="SZ", code="000001", factors=["alpha158_ma5", "alpha158_corr5", "alpha158_vwap0"]
    )
    result = _factor_result(req, data).data
    assert result["computed"] == ["alpha158_ma5"]
    assert set(result["errors"]) == {"alpha158_corr5", "alpha158_vwap0"}
    assert result["factor_definitions"]["alpha158_ma5"]["warmup_bars"] == 5
    assert FactorEvaluationRequest(
        stocks=[{"market": "SZ", "code": f"{i:06}"} for i in range(5)],
        factors=["alpha158_vma5"],
    ).factors == ["alpha158_vma5"]  # Runtime unit qualification is still mandatory.
    result = FactorEngine().compute_single(data, ["alpha158_ma5"])
    assert result.index.equals(data.index)


def test_reject_duplicate_dates_and_mixed_instruments():
    data = sample(10).reset_index(names="datetime")
    data.loc[9, "datetime"] = data.loc[8, "datetime"]
    with pytest.raises(ValueError, match="时间字段"):
        compute_alpha158(data, SPECS["MA5"])
    data = sample(10).assign(code=["000001"] * 5 + ["000002"] * 5)
    with pytest.raises(ValueError, match="单标的"):
        compute_alpha158(data, SPECS["MA5"])


def test_catalog_still_works_without_source_files_in_packaged_runtime(monkeypatch):
    def unavailable(_):
        raise OSError("source not bundled")

    monkeypatch.setattr("easy_tdx.factor.catalog.inspect.getsource", unavailable)
    definition = describe_factor(get_factor("alpha158_rank20"))
    assert definition["implementation_source_available"] is False
    assert definition["source_commit"] and len(definition["formula_sha256"]) == 64


@pytest.mark.parametrize("entry", entries(), ids=lambda entry: entry["id"])
def test_real_frozen_price_fixture_prefix_and_oracle(entry):
    # load_case verifies file and bar hashes. No volume/VWAP proxy is inserted.
    _, data, _ = load_case(entry)
    assert data.attrs["snapshot_metadata"]["actual_adjust"] == entry["adjust"]
    for key, spec in SPECS.items():
        if {"volume", "vwap"}.intersection(spec.inputs):
            continue  # These fixtures do not qualify canonical volume or VWAP.
        result = compute_alpha158(data, spec)
        for i in (spec.warmup - 1, len(data) - 1):
            if i < len(data):
                np.testing.assert_allclose(
                    result.iloc[i], oracle(data, key, i), atol=2e-10, rtol=2e-8
                )
        pd.testing.assert_series_equal(result.iloc[:100], compute_alpha158(data.iloc[:100], spec))
